### PR TITLE
Enable parallel builds.

### PR DESCRIPTION
**Pull request by davidgiven**
This changes the way submakes are invoked so that the -j flag is propagated, allowing parallel builds (which are much faster on my system!).

### CODE REVIEW

**Comment by astralaster** [comment]
We need to test the makefiles for parallelism first. I'm pretty sure the upload target for example runs while the firmware still compiles.

**Comment by davidgiven** [comment]
Yes, that didn't work. I've fixed it, but there's probably more similar issues.

**Comment by astralaster** [comment]
Can you please squash the two commits and rebase? I think with your fix to upload it's good to go.

**Review by astralaster — CHANGES_REQUESTED** [review]
Can you please squash the two commits and rebase? I think with your fix to upload it's good to go.

**Comment by davidgiven** [comment]
The stupid typos that were causing build failures are now fixed.

**Review by astralaster — APPROVED** [review]
Thanks for your work!

**Comment by astralaster** [comment]
> I've merged from trunk but I can't squash the commits (I'm not actually a git user...). But there should be an option to do it when merging via the github UI.

Thanks, I did not notice that yet.

**Pull request merged**
