### PR TITLE
Add a basic set of file I/O primitives.

### PR DESCRIPTION
**Pull request by davidgiven**
This is mostly for review purposes, to see whether you think I'm on the right track.

This adds completely untested support for basic stdio-like file access primitives; open, close, read, write, seek, tell, size, truncate. You can have up to eight files open, with user-side numbering. File offsets are 32 bits (but of course you can only read or write 64kB at a time).

I don't know how much spare memory the Pico has; each file structure contains a 512-byte buffer, so the eight files here use slightly more than 4kB.

Missing features: directory access, creating directories, deletion.

What do you think?

See also: https://github.com/davidgiven/cpm65/issues/55.

### CODE REVIEW

**Comment by paulscottrobson** [comment]
Pretty much what I had in mind.  If you are still okay with this what I suggest we do is to merge the pull request and assuming no issues (can't see why !) not document it immediately, just in case you need to tweak something.

**Comment by davidgiven** [comment]
Well, this is the easy bit. The next bit I need is directory listing, which will be much less fun.

BTW: I noticed that DSPGetString() always copies to a fixed size 32-byte buffer, which is a bit small for paths. Is there a reason why it does a copy rather than just returning a pointer to the string in cpuMemory? It should be nul-terminated there, and therefore safe to use.

Also, is ff compiled with long filename support?

**Comment by davidgiven** [comment]
(Also, happy to merge this. The biggest thing which might need tweaking are the return error numbers, which are currently just 0 or 1, but that can happen later.)

**Comment by leventp** [comment]
static const char* const modes[] = {
		"rb",	// 0: FIOMODE_READ
		"r+b", 	// 1: FIOMODE_WRITE
		"r+b",	// 2: FIOMODE_RDWR
		"w+b",	// 3: FIOMODE_CREATE
	};
	if (mode >= 3)
		return 1;

Not sure this is correct. mode can be 3.

**Comment by davidgiven** [comment]
Yikes. Yes, that's wrong. Fixed. I've also adjusted the FIOMODE constant names a bit for clarity.

**Comment by paulscottrobson** [comment]
Or, rather obviously (!) I could change the filing system functions in BASIC to use ASCIIZ and convert them there. This would not be particularly difficult and might actually be the best solution.

**Comment by davidgiven** [comment]
I've added an important missing feature, which is the ability to close all files (by trying to close file handle -1).

**Comment by paulscottrobson** [comment]
Would it be easier to convert the current system to ASCIIZ ?

**Comment by davidgiven** [comment]
I think that ASCIIZ is the more boring option, as it's the one which most C and assembler programmers will be used to (I just kind of assumed that myself, even _after_ I'd looked at the conversion function). So I think switching does make sense. But it would be really disruptive to users. neobasic itself isn't an issue, but there's a third-party Pascal --- is there anyone else?

From my side it makes no difference, as from machine code the difference between constructing a Pascal string vs a C string is a couple of instructions.

**Comment by paulscottrobson** [comment]
No, there's no one else. I'll ask the Pascal guy.

**Review by paulscottrobson — APPROVED** [review]
Fine. If you want to raise the potential number of files, that shouldn't be an issue.

**Pull request merged**
