### PR TITLE
USB mouse support

### PR DESCRIPTION
**Pull request by astralaster**
This adds USB mouse support to the API. I merged the existing cursor code with the mouse, so we don't track the same state two times.

The API just gets one new function (function 3 in group 11):

- Get mouse state
  - Param 0,1 as 16bit unsigned mouse position (screen pixel) in x
  - Param 2,3 as 16bit unsigned mouse position in y
  - Param 4 as single byte with bits for all mouse buttons (set when pressed)
  - Param 5 as single unsigned byte which represents scrollwheel state and increments or decrements on scrolls.

### CODE REVIEW

**Comment by paulscottrobson** [comment]
Shall (not) do.

**Comment by astralaster** [comment]
I think what's still missing is a query if a mouse is available. Because it would be not polite to activate the Cursor if there is no mouse connected.

**Review by paulscottrobson — APPROVED** [review]
Looks good. Can't test it as amazingly I do not have a single USB wired mouse.

**Comment by astralaster** [comment]
> Looks good. Can't test it as amazingly I do not have a single USB wired mouse.

My Logitech wireless dongle works, too.

**Pull request merged**
