### PR TITLE
MacOS build

### PR DESCRIPTION
**Pull request by omiq**
Successfully builds on MacOS on my Apple silicon machine, tiny changes thankfully!

### CODE REVIEW

**Comment by astralaster** [comment]
Good Job! I wonder if it is possible to also build it with GitHub action as we do for Windows currently. But even enabling builds from source for other Mac users is a great achievement.

**Review by paulscottrobson — DISMISSED** [review]
Looks fine.

**Comment by paulscottrobson** [comment]
Is there a need for all that _IMG_ASSET_ stuff ? It's just an array of constant uint8_t data ?

**Comment by omiq** [comment]
> Is there a need for all that _IMG_ASSET_ stuff ? It's just an array of constant uint8_t data ?

Without it there’s an error saying the parameter requires two elements, comma separated

**Comment by paulscottrobson** [comment]
I was thinking generally. It's just a pile of bytes, is there a reason we can't used static const uint8_t xxxx[] = { }; ? It has to be done for the 65C02 RAM which has to be aligned with a 64k block of RP2040 memory. Not sure anything else matters.

**Comment by astralaster** [comment]
> I was thinking generally. It's just a pile of bytes, is there a reason we can't used static const uint8_t xxxx[] = { }; ? It has to be done for the 65C02 RAM which has to be aligned with a 64k block of RP2040 memory. Not sure anything else matters.
I thought the 64k alignment was lifted? It was just a premeasure for DMA to work on the 6502 memory block, but we dropped the DMA idea.

**Comment by astralaster** [comment]
I've locally tested that changing it to static const does still work for the emulator. Just need some time to update this PR.

**Review by paulscottrobson — APPROVED** [review]
Needs to be rechecked by Omid

**Review by astralaster — CHANGES_REQUESTED** [review]
Stiil needs work on the #ifdef WINDOWS part.

**Pull request closed without merging**
