### PR TITLE
Second try at the console changes

### PR DESCRIPTION
**Pull request by davidgiven**
This should fix the CONWriteString weirdness, which was caused by misuse of varargs. (On some platforms, like ARM, a `va_list` is a scalar and is passed to vsnprintf by value. On x86, it's an array, and is passed by reference, meaning that passing the same `va_list` to two different calls to vsnprintf won't work.)

### CODE REVIEW

**Comment by davidgiven** [comment]
Do not merge. Something's not right. Investigating.

**Comment by davidgiven** [comment]
I think this is ready to go now.

**Comment by davidgiven** [comment]
Is there anything else you need for this?

**Comment by paulscottrobson** [comment]
What's the current state of play on this ? Did you figure out the bug ?

**Comment by davidgiven** [comment]
Yes, it should be all good to go now.

**Pull request merged**
