### PR TITLE
Add support for filesystem error codes.

### PR DESCRIPTION
**Pull request by davidgiven**
These are returned in the error field in the mailbox. 0 is OK, 1 is UNKNOWN (for backwards compatibility), and other values are defined.

Currently this contains the interface plus an implementation for the emulator. I'll add the real firmware code (and documentation) if people think this looks good.

### CODE REVIEW

**Comment by davidgiven** [comment]
This is a draft. Please don't merge! (Didn't there used to be an option somewhere for marking PRs as drafts?)

**Comment by paulscottrobson** [comment]
Looks good. Let me know when you want it merged.

**Comment by astralaster** [comment]
Converted it to draft. Its just one click at the right column in this view. :)

**Comment by davidgiven** [comment]
I haven't had a chance to test this yet, but here's the new proposal. I've just copied all the fatfs error codes so there's a 1:1 mapping, and then updated the emulator code to produce what's hopefully the same ones.

This isn't ready to merge yet; I've run out of time for today and will get the chance to test it tomorrow, but I wanted to know if this is a viable approach. The fatfs error codes are unfortunately pretty ambiguous which means too many things just become FR_DENIED (like out of disk errors).

**Comment by paulscottrobson** [comment]
No rush. I don't have a problem if this isn't ready for 1.0.0 because it's an enhancement, it just allows identification of what the error is.

**Comment by davidgiven** [comment]
Okay, that's all ready to go, barring the documentation --- where should this go?

I've also rearranged the error codes to make them easier to parse; the top four bits contain the error class. This should help most programs that only really care between 'file not found / permission denied / disk error'.

**Comment by paulscottrobson** [comment]
Depends. If it is really a document then it should go in the API reference which is markup. There is a repo neo6502-documents you can PR or you can just send me the text.

**Comment by davidgiven** [comment]
Sent via https://github.com/paulscottrobson/neo6502-documents/pull/8.

**Pull request merged**
