### PR TITLE
Add some console API functions.

### PR DESCRIPTION
**Pull request by davidgiven**
The only really new piece of functionality here is insert/delete line (which is super flexible as it can be used for scrolling in both directions as well as other things). Everything else is just internal console functionality, exposed through the API.

### CODE REVIEW

**Review by paulscottrobson — CHANGES_REQUESTED** [review]
Hi. No problem with this, can you replace the 320 with graphMode->xGSize as those 320 magic constants shouldn't be there. It was me that put them in first :)

**Review by paulscottrobson — APPROVED** [review]

**Comment by paulscottrobson** [comment]
One thing.  The cat function was crashing in the emulator. After some investigation it seemed to be that it didn't like the CONWriteString("%s\r",buffer.c_str()); instruction.

This worked fine, however, if split up into two calls. Do you have any idea why this might be the case ? As you probably noticed, I write very little C++.

**Comment by paulscottrobson** [comment]
This has now been reverted as it is not working. See the Revert PR #133

**Comment by davidgiven** [comment]
Sorry about that --- looking into it.

**Comment by paulscottrobson** [comment]
Don't worry, it happens :) I did look but I thought you might find it easier to fix. I suspect it's something fairly simple. 

Incidentally, I've also tweaked a minor bug in the file system on the emulator and now use the handle stuff for read/write files rather than have multiple read/write functions ; this is largely so I can just have one version of the extended file format. At present I'm just using handle zero as it looks like these are allocated by the developer, what should I use, the last one ?

**Pull request merged**
